FROM node:14

RUN mkdir -p /usr/share/www
WORKDIR /usr/share/www

RUN npm i open-api-mocker@1.7.2

COPY ./api ./api

EXPOSE 8080

ENTRYPOINT ["./node_modules/.bin/open-api-mocker"]
CMD ["-s", "./api/payment-initiation-openapi-basic-auth.yaml", "-p", "8080"]